// Datos de demostración: se usan cuando no hay credenciales de Supabase
// (modo demo) para poder desarrollar y revisar la UI. No van a producción.
// Reflejan el ICP amplio (cualquier sector) y la ficha estilo Explee.
import type { BriefingLead } from './types';

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const DEMO_LEADS: BriefingLead[] = [
  {
    lead: {
      id: 'demo-lead-1',
      company_id: 'demo-co-1',
      contact_id: 'demo-ct-1',
      scan_id: 'demo-sc-1',
      stage: 'briefed',
      priority_score: 87,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-1',
      name: 'Acme Labs',
      domain: 'acmelabs.io',
      description: 'Infraestructura de pagos para marketplaces B2B',
      hq_country: 'ES',
      sector: 'fintech',
      source: 'rss',
      created_at: daysAgo(4),
      linkedin_url: 'https://www.linkedin.com/company/acmelabs',
      size: '11-50',
      city: 'Madrid',
      founded_year: 2024,
      funding_stage: 'seed',
      determinants: [
        'Cobros y pagos en una sola integración para marketplaces',
        'Liquidación en 24h frente a los 7 días del estándar',
        'Onboarding de vendedor sin fricción KYC',
      ],
      competitors: [
        { name: 'Stripe Connect', domain: 'stripe.com' },
        { name: 'Adyen for Platforms', domain: 'adyen.com' },
        { name: 'Mangopay', domain: 'mangopay.com' },
      ],
      keywords: ['pagos b2b', 'marketplace', 'liquidación', 'kyc', 'fintech'],
      icp_fit: 92,
      icp_reason: 'Seed reciente, equipo de 20, fintech B2B con producto lanzado.',
    },
    signal: {
      id: 'demo-sg-1',
      company_id: 'demo-co-1',
      type: 'funding_round',
      detail: {
        round: 'seed',
        amount: '2.4M EUR',
        investors: ['Kfund'],
        source_url: 'https://www.eu-startups.com/demo',
      },
      detected_at: daysAgo(4),
    },
    scan: {
      id: 'demo-sc-1',
      company_id: 'demo-co-1',
      scanner_job_id: 1001,
      status: 'ready',
      score: 34,
      tldr: {
        summary:
          'Identidad genérica, web sobre template, cero sistema de voz. La propuesta de valor está enterrada bajo jerga de sector.',
      },
      evidence: {
        gaps: ['Web construida sobre template estándar', 'Sin sistema de voz definido'],
      },
      result_raw: null,
      ui_url: 'https://brand3.fly.dev/scanner/1001',
      created_at: daysAgo(1),
      completed_at: daysAgo(1),
    },
    contact: {
      id: 'demo-ct-1',
      company_id: 'demo-co-1',
      lusha_id: null,
      full_name: 'Jane Doe',
      role: 'CEO & Co-founder',
      email: 'jane@acmelabs.io',
      linkedin_url: 'https://www.linkedin.com/in/janedoe',
      linkedin_handle: 'janedoe',
      headline: 'Building payments infra for B2B marketplaces · ex-Stripe',
      source: 'explee',
      notes: null,
      enriched_at: daysAgo(0),
      last_touch_at: null,
      email_verified: true,
    },
    message: {
      id: 'demo-msg-1',
      lead_id: 'demo-lead-1',
      channel: 'linkedin',
      lang: 'es',
      draft:
        'Jane, vi la ronda con Kfund. Mirando vuestra web me llamó la atención que la propuesta de pagos B2B queda enterrada bajo el template. Con el momento que tenéis, ¿os habéis planteado ya cómo contar Acme cuando el producto escale?',
      edited_final: null,
      sent_at: null,
      replied: false,
      created_at: daysAgo(0),
    },
  },
  {
    lead: {
      id: 'demo-lead-2',
      company_id: 'demo-co-2',
      contact_id: 'demo-ct-2',
      scan_id: 'demo-sc-2',
      stage: 'briefed',
      priority_score: 74,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-2',
      name: 'Verdeo',
      domain: 'verdeo.eu',
      description: 'Software de trazabilidad de huella de carbono para pymes industriales',
      hq_country: 'DE',
      sector: 'saas',
      source: 'explee',
      created_at: daysAgo(6),
      linkedin_url: 'https://www.linkedin.com/company/verdeo',
      size: '11-50',
      city: 'Berlín',
      founded_year: 2023,
      funding_stage: 'series-a',
      determinants: [
        'Trazabilidad automática desde ERP sin consultoría',
        'Cumple CSRD sin equipo de sostenibilidad propio',
        'Precio por planta, no por usuario',
      ],
      competitors: [
        { name: 'Plan A', domain: 'plana.earth' },
        { name: 'Cozero', domain: 'cozero.io' },
      ],
      keywords: ['csrd', 'huella de carbono', 'erp', 'industria', 'compliance'],
      icp_fit: 78,
      icp_reason: 'Serie A reciente, 40 personas, SaaS B2B en mercado regulado en expansión.',
    },
    signal: {
      id: 'demo-sg-2',
      company_id: 'demo-co-2',
      type: 'funding_round',
      detail: {
        round: 'series-a',
        amount: '8M EUR',
        investors: ['Cherry Ventures', 'Fabric VC'],
        source_url: 'https://sifted.eu/demo',
      },
      detected_at: daysAgo(6),
    },
    scan: {
      id: 'demo-sc-2',
      company_id: 'demo-co-2',
      scanner_job_id: 1002,
      status: 'ready',
      score: 52,
      tldr: {
        summary:
          'Marca funcional pero indistinguible de otras cinco herramientas de compliance. El naming promete más de lo que la identidad entrega.',
      },
      evidence: {
        gaps: ['Identidad indistinguible del sector', 'Sin narrativa de confianza'],
      },
      result_raw: null,
      ui_url: 'https://brand3.fly.dev/scanner/1002',
      created_at: daysAgo(1),
      completed_at: daysAgo(1),
    },
    contact: {
      id: 'demo-ct-2',
      company_id: 'demo-co-2',
      lusha_id: null,
      full_name: 'Max Weber',
      role: 'Co-founder & CEO',
      email: null,
      linkedin_url: 'https://www.linkedin.com/in/maxweber',
      linkedin_handle: 'maxweber',
      headline: 'Making carbon reporting boring · Co-founder @ Verdeo',
      source: 'explee',
      notes: 'Publica sobre regulación CSRD, tono técnico',
      enriched_at: daysAgo(0),
      last_touch_at: null,
      email_verified: false,
    },
    message: {
      id: 'demo-msg-2',
      lead_id: 'demo-lead-2',
      channel: 'linkedin',
      lang: 'en',
      draft:
        'Max, noticed Verdeo sits visually next to five other compliance tools, same green, same dashboards. With the Series A closed, the trust story becomes the product. How are you planning to tell it?',
      edited_final: null,
      sent_at: null,
      replied: false,
      created_at: daysAgo(0),
    },
  },
  {
    lead: {
      id: 'demo-lead-3',
      company_id: 'demo-co-3',
      contact_id: 'demo-ct-3',
      scan_id: 'demo-sc-3',
      stage: 'detected',
      priority_score: 91,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-3',
      name: 'Nura Health',
      domain: 'nura.health',
      description: 'Agentes de IA para la gestión administrativa de clínicas privadas',
      hq_country: 'ES',
      sector: 'health',
      source: 'engaged',
      created_at: daysAgo(2),
      linkedin_url: 'https://www.linkedin.com/company/nurahealth',
      size: '1-10',
      city: 'Barcelona',
      founded_year: 2025,
      funding_stage: 'pre-seed',
      determinants: [
        'Automatiza la parte administrativa, no el diagnóstico',
        'Integra con el software de gestión clínica ya instalado',
      ],
      competitors: [{ name: 'Doctoralia', domain: 'doctoralia.es' }],
      keywords: ['clínicas', 'automatización', 'agentes ia', 'salud privada'],
      icp_fit: 85,
      icp_reason: 'Pre-seed, 6 personas, en lanzamiento. Founder interactuó con posts de Sergio.',
    },
    signal: {
      id: 'demo-sg-3',
      company_id: 'demo-co-3',
      type: 'engagement',
      detail: { source_url: 'https://www.linkedin.com/posts/sergio-demo' },
      detected_at: daysAgo(2),
    },
    scan: {
      id: 'demo-sc-3',
      company_id: 'demo-co-3',
      scanner_job_id: 1003,
      status: 'running',
      score: null,
      tldr: null,
      evidence: null,
      result_raw: null,
      ui_url: null,
      created_at: daysAgo(0),
      completed_at: null,
    },
    contact: {
      id: 'demo-ct-3',
      company_id: 'demo-co-3',
      lusha_id: null,
      full_name: 'Laura Sanz',
      role: 'Founder',
      email: null,
      linkedin_url: 'https://www.linkedin.com/in/laurasanz',
      linkedin_handle: 'laurasanz',
      headline: 'Founder @ Nura Health · Menos papeleo, más consulta',
      source: 'linkedin',
      notes: 'Comentó el post sobre marcas que no aguantan el pivot',
      enriched_at: null,
      last_touch_at: null,
      email_verified: false,
    },
    message: null,
  },
];
