// Datos de demostración: se usan cuando no hay credenciales de Supabase
// (modo demo) para poder desarrollar y revisar la UI. No van a producción.
import type { BriefingLead } from './types';

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const DEMO_LEADS: BriefingLead[] = [
  {
    lead: {
      id: 'demo-lead-1',
      company_id: 'demo-co-1',
      contact_id: 'demo-ct-1',
      scan_id: 'demo-sc-1',
      stage: 'briefed',
      priority_score: 87,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-1',
      name: 'Acme Labs',
      domain: 'acmelabs.io',
      description: 'Infraestructura de pagos para marketplaces B2B',
      hq_country: 'Spain',
      sector: 'marketplace',
      source: 'rss',
      created_at: daysAgo(4),
    },
    signal: {
      id: 'demo-sg-1',
      company_id: 'demo-co-1',
      type: 'funding_round',
      detail: {
        round: 'seed',
        amount: '2.4M EUR',
        investors: ['Kfund'],
        source_url: 'https://www.eu-startups.com/demo',
      },
      detected_at: daysAgo(4),
    },
    scan: {
      id: 'demo-sc-1',
      company_id: 'demo-co-1',
      scanner_job_id: 1001,
      status: 'ready',
      score: 34,
      tldr: {
        summary:
          'Identidad genérica, web sobre template, cero sistema de voz. La propuesta de valor está enterrada bajo jerga de sector.',
      },
      evidence: {
        gaps: ['Web construida sobre template estándar', 'Sin sistema de voz definido'],
      },
      result_raw: null,
      ui_url: 'https://brand3.fly.dev/scanner/1001',
      created_at: daysAgo(1),
      completed_at: daysAgo(1),
    },
    contact: {
      id: 'demo-ct-1',
      company_id: 'demo-co-1',
      lusha_id: null,
      full_name: 'Jane Doe',
      role: 'CEO',
      email: 'jane@acmelabs.io',
      linkedin_url: 'https://www.linkedin.com/in/janedoe',
      notes: null,
      enriched_at: daysAgo(0),
    },
    message: {
      id: 'demo-msg-1',
      lead_id: 'demo-lead-1',
      channel: 'linkedin',
      lang: 'es',
      draft:
        'Jane, vi la ronda con Kfund. Mirando vuestra web me llamó la atención que la propuesta de pagos B2B queda enterrada bajo el template. Con el momento que tenéis, ¿os habéis planteado ya cómo contar Acme cuando el producto escale?',
      edited_final: null,
      sent_at: null,
      replied: false,
      created_at: daysAgo(0),
    },
  },
  {
    lead: {
      id: 'demo-lead-2',
      company_id: 'demo-co-2',
      contact_id: 'demo-ct-2',
      scan_id: 'demo-sc-2',
      stage: 'briefed',
      priority_score: 74,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-2',
      name: 'Vaultly',
      domain: 'vaultly.xyz',
      description: 'Custodia de activos digitales para fondos',
      hq_country: 'Germany',
      sector: 'web3',
      source: 'lusha_signal',
      created_at: daysAgo(6),
    },
    signal: {
      id: 'demo-sg-2',
      company_id: 'demo-co-2',
      type: 'funding_round',
      detail: {
        round: 'series-a',
        amount: '8M USD',
        investors: ['Cherry Ventures', 'Fabric VC'],
        source_url: 'https://sifted.eu/demo',
      },
      detected_at: daysAgo(6),
    },
    scan: {
      id: 'demo-sc-2',
      company_id: 'demo-co-2',
      scanner_job_id: 1002,
      status: 'ready',
      score: 52,
      tldr: {
        summary:
          'Marca funcional pero indistinguible de otras cinco custodias. El naming promete más de lo que la identidad entrega.',
      },
      evidence: { gaps: ['Identidad indistinguible del sector', 'Sin narrativa de confianza'] },
      result_raw: null,
      ui_url: 'https://brand3.fly.dev/scanner/1002',
      created_at: daysAgo(1),
      completed_at: daysAgo(1),
    },
    contact: {
      id: 'demo-ct-2',
      company_id: 'demo-co-2',
      lusha_id: null,
      full_name: 'Max Weber',
      role: 'Co-founder & CEO',
      email: null,
      linkedin_url: 'https://www.linkedin.com/in/maxweber',
      notes: 'Publica sobre seguridad institucional, tono técnico',
      enriched_at: daysAgo(0),
    },
    message: {
      id: 'demo-msg-2',
      lead_id: 'demo-lead-2',
      channel: 'linkedin',
      lang: 'en',
      draft:
        'Max, noticed Vaultly sits visually next to five other custody brands, same palette, same vault metaphors. With the Series A closed, the trust story becomes the product. How are you planning to tell it?',
      edited_final: null,
      sent_at: null,
      replied: false,
      created_at: daysAgo(0),
    },
  },
  {
    lead: {
      id: 'demo-lead-3',
      company_id: 'demo-co-3',
      contact_id: null,
      scan_id: 'demo-sc-3',
      stage: 'detected',
      priority_score: 91,
      discard_reason: null,
      updated_at: daysAgo(0),
    },
    company: {
      id: 'demo-co-3',
      name: 'Nura Health',
      domain: 'nura.health',
      description: 'Agentes de IA para clínicas privadas',
      hq_country: 'Spain',
      sector: 'ai',
      source: 'engaged',
      created_at: daysAgo(2),
    },
    signal: {
      id: 'demo-sg-3',
      company_id: 'demo-co-3',
      type: 'engagement',
      detail: { source_url: 'https://www.linkedin.com/posts/sergio-demo' },
      detected_at: daysAgo(2),
    },
    scan: {
      id: 'demo-sc-3',
      company_id: 'demo-co-3',
      scanner_job_id: 1003,
      status: 'running',
      score: null,
      tldr: null,
      evidence: null,
      result_raw: null,
      ui_url: null,
      created_at: daysAgo(0),
      completed_at: null,
    },
    contact: null,
    message: null,
  },
];
