// Nombres de pila frecuentes (es/pt/en/fr/it/de/in), en minúsculas.
// Sirven solo como heurística para partir nombres pegados tipo
// "joaocurado" → "Joao Curado". No es un censo: si un nombre no está,
// simplemente no se parte (nunca inventamos cortes).
export const GIVEN_NAMES = new Set([
  // Español
  'alberto', 'alejandro', 'alicia', 'alvaro', 'ana', 'andrea', 'andres',
  'angel', 'angela', 'antonio', 'beatriz', 'begona', 'blanca', 'borja',
  'carlos', 'carmen', 'carolina', 'cesar', 'clara', 'claudia', 'cristina',
  'daniel', 'david', 'diego', 'dolores', 'elena', 'elisa', 'emilio',
  'enrique', 'ernesto', 'esther', 'eva', 'federico', 'felipe', 'fernando',
  'francisco', 'gabriel', 'gloria', 'gonzalo', 'guillermo', 'hector',
  'hugo', 'ignacio', 'ines', 'irene', 'isabel', 'ivan', 'jaime', 'javier',
  'jesus', 'joaquin', 'jorge', 'jose', 'josep', 'juan', 'julia', 'julio',
  'laura', 'leticia', 'lorena', 'lourdes', 'lucas', 'lucia', 'luis',
  'manuel', 'marcos', 'margarita', 'maria', 'mariano', 'marina', 'marta',
  'mercedes', 'miguel', 'monica', 'natalia', 'nerea', 'nicolas', 'noelia',
  'nuria', 'olga', 'oscar', 'pablo', 'paloma', 'patricia', 'paula',
  'pedro', 'pilar', 'rafael', 'ramon', 'raquel', 'raul', 'ricardo',
  'roberto', 'rocio', 'rodrigo', 'rosa', 'ruben', 'salvador', 'santiago',
  'sara', 'sergio', 'silvia', 'sofia', 'sonia', 'susana', 'teresa',
  'tomas', 'vanesa', 'veronica', 'vicente', 'victor', 'victoria',
  'virginia', 'xavier', 'yolanda',
  // Portugués
  'afonso', 'andre', 'antonio', 'beatriz', 'bruno', 'carlota', 'catarina',
  'diogo', 'duarte', 'filipa', 'filipe', 'francisca', 'goncalo',
  'henrique', 'joana', 'joao', 'leonor', 'luisa', 'madalena', 'mariana',
  'martim', 'matilde', 'miguel', 'nuno', 'paulo', 'rita', 'rui', 'tiago',
  'vasco',
  // Inglés
  'aaron', 'adam', 'alan', 'albert', 'alex', 'alexander', 'alice',
  'amanda', 'amber', 'amy', 'andrew', 'anna', 'anne', 'anthony', 'ashley',
  'austin', 'barbara', 'benjamin', 'brandon', 'brian', 'bruce', 'carl',
  'catherine', 'charles', 'charlotte', 'chris', 'christian', 'christine',
  'christopher', 'craig', 'daniel', 'danielle', 'dennis', 'diana',
  'donald', 'dorothy', 'douglas', 'dylan', 'edward', 'elizabeth', 'emily',
  'emma', 'eric', 'ethan', 'eugene', 'frank', 'george', 'gerald', 'grace',
  'gregory', 'hannah', 'harold', 'harry', 'heather', 'helen', 'henry',
  'jack', 'jacob', 'james', 'jason', 'jeffrey', 'jennifer', 'jeremy',
  'jessica', 'john', 'jonathan', 'jordan', 'joseph', 'joshua', 'joyce',
  'judith', 'julie', 'justin', 'karen', 'katherine', 'kathleen', 'keith',
  'kelly', 'kevin', 'kimberly', 'kyle', 'larry', 'lauren', 'lawrence',
  'linda', 'lisa', 'logan', 'louis', 'madison', 'margaret', 'mark',
  'martha', 'martin', 'mary', 'matthew', 'megan', 'melissa', 'michael',
  'michelle', 'nancy', 'natalie', 'nathan', 'nicholas', 'nicole', 'noah',
  'olivia', 'pamela', 'patrick', 'paul', 'peter', 'philip', 'rachel',
  'ralph', 'raymond', 'rebecca', 'richard', 'robert', 'roger', 'ronald',
  'rose', 'russell', 'ruth', 'ryan', 'samantha', 'samuel', 'sandra',
  'sarah', 'scott', 'sean', 'sharon', 'sophia', 'stephanie', 'stephen',
  'steven', 'susan', 'terry', 'thomas', 'timothy', 'tyler', 'vincent',
  'walter', 'wayne', 'william', 'zachary',
  // Francés / Italiano / Alemán / Nórdico
  'alessandro', 'anders', 'antoine', 'chiara', 'claude', 'elena', 'elisa',
  'federica', 'felix', 'francesca', 'francesco', 'francois', 'giacomo',
  'giovanni', 'giulia', 'giuseppe', 'hans', 'jan', 'jean', 'julien',
  'klaus', 'lars', 'laurent', 'lorenzo', 'luca', 'lukas', 'marcel',
  'marco', 'matteo', 'mathieu', 'nicolas', 'niels', 'olivier', 'pierre',
  'riccardo', 'simone', 'stefan', 'stefano', 'sven', 'thomas', 'valentina',
  // India / otros
  'abhishek', 'aditya', 'ajay', 'amit', 'anil', 'anjali', 'ankit',
  'arjun', 'ashok', 'deepak', 'gaurav', 'karan', 'kavita', 'manoj',
  'neha', 'nikhil', 'pooja', 'pradeep', 'priya', 'rahul', 'rajesh',
  'ramesh', 'ravi', 'rohit', 'sanjay', 'sneha', 'sunil', 'suresh',
  'varun', 'vijay', 'vikram',
]);
